In [1]:
import numpy as np

In [2]:
Student_data = np.array([
    [85,90,78],
    [92,88,95],
    [75,80,70],
    [98,96,94]
])

In [3]:
print(Student_data)

[[85 90 78]
 [92 88 95]
 [75 80 70]
 [98 96 94]]


In [4]:
print(Student_data.shape)

(4, 3)


In [9]:
Multiply = np.array([
    [1],
    [1],
    [1]
])

In [6]:
print(Multiply)

[[1], [1], [1]]


In [10]:
print(Multiply.shape)

(3, 1)


In [11]:
Total_mark = Student_data @ Multiply

In [12]:
print(Total_mark)

[[253]
 [275]
 [225]
 [288]]
